# 数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rong_video?serverTimezone=UTC
    username: root
    password: a123456
    # 连接池
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      stat-view-servlet:
        allow: true

# mybatis
mybatis:
  # mapper映射文件路径
  mapper-locations: classpath:mapper/*Mapper.xml
  # 配置别名
  typeAliasesPackage: com.rong.pojo

# Mapper
mapper:
  mappers: com.rong.utils.MyMapper
  not-empty: false
  identity: MYSQL

# redis 配置
redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

# 分页插件
pagehelper:
  helper-dialect: mysql
  support-methods-arguments: true
  params: count=countSql


